### ISSUE TITLE
AttributeError: 'BaseModelOutput' object has no attribute 'size'

### ISSUE THREAD

**Issue by lindylin1817** [OpenBMB/BMCook#14]
When run the example for gpt2 with gpt-example/train.py, I got the following error:
```
Traceback (most recent call last):
  File "train.py", line 271, in <module>
    main()
  File "train.py", line 230, in main
    outputs = Trainer.forward(model, None, None, dec_input, dec_length, targets, loss_func)
  File "/home/xwv/xwv/BMCook-main/bmcook/distilling/__init__.py", line 43, in forward
    outputs = foward_fn(
  File "train.py", line 79, in forward
    batch, seq_len, vocab_out_size = logits.size()
AttributeError: 'BaseModelOutput' object has no attribute 'size'

```
Should I correct anything here? Thanks!

**Comment by gongbaitao** [comment]
Hi, it's a version difference of ModelCenter. The example is based on model-center-0.1.3 or older but Pypi version is 0.1.5 now. In v0.1.5, `logits` is an attribute of `BaseModelOutput` class. 
So briefly, replacing 
`logits = outputs` by `logits = outputs.logits` in file `train.py`, line 74, may be helpful.

**Comment by lindylin1817** [comment]
> I tried the modification mentioned above (replacing logits = outputs by logits = outputs.logits), but it doesn't work ...
Actually, I got another issue before going into this line. The error is for the following code line. 

```
    def new_forward(model_self, enc_input, enc_length, dec_input, dec_length, return_logits=False):
        return model_self.forward_old(dec_input, dec_length, return_logits=return_logits)
```
I got the following error.

```
Traceback (most recent call last):
  File "train.py", line 271, in <module>
    main()
  File "train.py", line 230, in main
    outputs = Trainer.forward(model, None, None, dec_input, dec_length, targets, loss_func)
  File "/home/xwv/xwv/BMCook-main/bmcook/distilling/__init__.py", line 43, in forward
    outputs = foward_fn(
  File "train.py", line 74, in forward
    outputs = model(
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "train.py", line 112, in new_forward
    return model_self.forward_old(dec_input, dec_length, return_logits=return_logits)
TypeError: forward() got an unexpected keyword argument 'return_logits'

```
Thus, I tried to avoid it by modifying the code 
`return model_self.forward_old(dec_input, dec_length, return_logits=return_logits)`
into
`return model_self.forward_old(dec_input, dec_length)`

I don't know if such modification make sense or not. Or are these errors =relevant? Thanks for help!

**Comment by lindylin1817** [comment]
OK, I found the root cause. In model-center/model/gpt2.py, the forward function uses `output_logits` as the parameter to control if logits being output or not. But in BMCook, the `gpt2-example/train.py` as well as `distilling/__init__.py` uses `return_logits `wrongly. 
After I changed all the `return_logits ` into `output_logits`, it works. So, you might correct them in BMCook. Thanks!

**Comment by gongbaitao** [comment]
The bug has been fixed in branch `model-center` and we update the `README.md` in `gpt-example`. Thanks for your issue feedback!
