### ISSUE TITLE
Is there a way to do pruning/quantization without distillation?

### ISSUE THREAD

**Issue by Smu-Tan** [OpenBMB/BMCook#18]
Hi!

Could you let me know if there is a way to do pruning/quantization without distillation?

**Comment by Smu-Tan** [comment]
And also could you specify the packages' versions including bmtrain?

**Comment by gongbaitao** [comment]
Sorry for the delay.
You can set the config.json according to [utils/config.py](https://github.com/OpenBMB/BMCook/blob/main/bmcook/utils/config.py).  Setting `scale` arguments to 0 will close distillation.
Now bmtrain>=0.2.0 is needed.

**Comment by Smu-Tan** [comment]
Thanks for the info!
